version: '3'

services:
  jupyter:
    build: .
    restart: always
    working_dir: /workspace
    volumes:
      - .jupyter:/root/.jupyter
      - .:/workspace
    ports:
      - 8888:8888
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 'all'
                capabilities: [gpu]